version: '2'
services:
  database:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: transport_database
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: P@ssw0rd
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - ./database:/home/database
